"""user middle name nullable

Revision ID: 3cfc57de6e00
Revises: c645b5296a0a
Create Date: 2026-05-13 14:41:12.932348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3cfc57de6e00'
down_revision: Union[str, Sequence[str], None] = 'c645b5296a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'middle_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'middle_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
