"""outstanding and blacklisttoken store

Revision ID: 888cc542bb0b
Revises: f4583e3f82ee
Create Date: 2026-05-13 17:03:38.019408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '888cc542bb0b'
down_revision: Union[str, Sequence[str], None] = 'f4583e3f82ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outstandingtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outstandingtoken_jti'), 'outstandingtoken', ['jti'], unique=True)
    op.create_table('blacklistedtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Integer(), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['token'], ['outstandingtoken.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklistedtoken')
    op.drop_index(op.f('ix_outstandingtoken_jti'), table_name='outstandingtoken')
    op.drop_table('outstandingtoken')
    # ### end Alembic commands ###
